framework:
    asset_mapper:
        # Racine unique des assets (recommandé Symfony 7)
        paths:
            - assets

        # En dev : on veut des erreurs strictes
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            # En prod : warning seulement (tolérance)
            missing_import_mode: warn
