framework:
    asset_mapper:
        # Les rÃ©pertoires sources pour les assets publics
        paths:
            - assets/images/static
            - assets/images/pages
            - assets/images/users
            - assets/css
            - assets/js
            - assets/fonts

        # Comportement lorsqu'un import est introuvable
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
