monolog:
    channels:
        - deprecation
        - sso
        - agduc

########################################
# DEV
########################################
when@dev:
    monolog:
        handlers:
            # ================================
            # LOGS GENERAUX DEV
            # ================================
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!sso", "!agduc"]

            # ================================
            # LOGS SSO
            # ================================
            sso:
                type: stream
                path: "%kernel.logs_dir%/sso.log"
                level: info
                channels: ["sso"]

            # ================================
            # LOGS METIER AGDUC
            # ================================
            agduc:
                type: stream
                path: "%kernel.logs_dir%/agduc.log"
                level: info
                channels: ["agduc"]

            # ================================
            # CONSOLE
            # ================================
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!sso", "!agduc"]

########################################
# TEST
########################################
when@test:
    monolog:
        handlers:
            # ================================
            # LOGS GENERAUX TEST
            # ================================
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!sso", "!agduc"]

            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

            # ================================
            # LOGS SSO TEST
            # ================================
            sso:
                type: stream
                path: "%kernel.logs_dir%/sso_test.log"
                level: debug
                channels: ["sso"]

            # ================================
            # LOGS AGDUC TEST
            # ================================
            agduc:
                type: stream
                path: "%kernel.logs_dir%/agduc_test.log"
                level: debug
                channels: ["agduc"]

########################################
# PROD
########################################
when@prod:
    monolog:
        handlers:
            # ================================
            # LOGS GENERAUX PROD
            # ================================
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!deprecation", "!sso", "!agduc"]

            nested:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json

            # ================================
            # LOGS SSO / AUTH
            # ================================
            sso:
                type: stream
                path: "%kernel.logs_dir%/sso.log"
                level: info
                formatter: monolog.formatter.json
                channels: ["sso"]

            # ================================
            # LOGS METIER AGDUC
            # ================================
            agduc:
                type: stream
                path: "%kernel.logs_dir%/agduc.log"
                level: info
                formatter: monolog.formatter.json
                channels: ["agduc"]

            # ================================
            # CONSOLE PROD
            # ================================
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!sso", "!agduc"]

            # ================================
            # DEPRECATIONS
            # ================================
            deprecation:
                type: stream
                path: php://stderr
                channels: [deprecation]
                formatter: monolog.formatter.json
