framework:
    router:
        # Génération d’URL hors HTTP (CLI, tests, workers)
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
