security:

    # =====================================================================
    #  HASHERS
    # =====================================================================
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # =====================================================================
    #  USER PROVIDER pour SSO
    # =====================================================================
    providers:
        sso_provider:
            id: App\Security\SsoUserProvider

    # =====================================================================
    #  FIREWALLS
    # =====================================================================
    firewalls:

        # Désactive la sécurité dans l'environnement dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: sso_provider

            custom_authenticators:
                - App\Security\SsoAuthenticator

            # Quand Symfony doit authentifier quelqu’un, il utilise ton authenticator SSO
            entry_point: App\Security\SsoAuthenticator

            logout:
                path: /logout

            # Pas de stateless → session utilisée
            stateless: false

    # =====================================================================
    #  ACCESS CONTROL
    # =====================================================================
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }


# =====================================================================
# CONFIG TEST
# =====================================================================
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
