security:
    enable_authenticator_manager: true

    # Pas de password hasher nécessaire pour le SSO
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    # =====================================================================
    #  USER PROVIDER POUR SSO
    # =====================================================================
    providers:
        sso_provider:
            id: App\Security\SsoUserProvider

    # =====================================================================
    #  FIREWALL PRINCIPAL
    # =====================================================================
    firewalls:

        # Firewall dev : pas de sécurité
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: sso_provider
            custom_authenticators:
                - App\Security\SsoAuthenticator
            entry_point: App\Security\SsoAuthenticator
            logout:
                path: /logout

    # =====================================================================
    # ACCESS CONTROL
    # =====================================================================
    access_control:
        - { path: ^/admin,   roles: ROLE_ADMIN }
        - { path: ^/,        roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
