twig:
    file_name_pattern: '*.twig'

    # Dossier racine des templates
    default_path: '%kernel.project_dir%/templates'

    # Namespaces Twig (alignés avec l’arborescence réelle)
    paths:
        '%kernel.project_dir%/templates/layout': layout
        '%kernel.project_dir%/templates/partials': partials
        '%kernel.project_dir%/templates/security': security


when@test:
    twig:
        strict_variables: true
